### ISSUE TITLE
Use helper function to get business logic out of templates wherever possible

### ISSUE THREAD

**Issue by mandiwise** [redacademy/granville-spring-2017#13]
Code such as this (in `page-programs.php`) can be abstracted away into helper functions:

```
$program_types = get_terms(array (
  'taxonomy' => 'program-type',
  'hide_empty' => false
)); 

foreach($program_types as $key => $val) {
  if($val->slug == 'information') {
    $item = $program_types[$key];
    unset($program_types[$key]);
    array_push($program_types, $item); 
    break;
  }
}
```

**Comment by kmsolberg** [comment]
Should I create a function and then call it on the programs template? Or should the whole function be moved to extras.php?

**Comment by kmsolberg** [comment]
Hey @mandiwise - I tried putting it in a helper function from extras and it's not working properly - is it ok to leave this one instance in the template file?

**Comment by kmsolberg** [comment]
Added in helper function, commit #e92a902.
