### ISSUE TITLE
Leave index.php as "default" as possible

### ISSUE THREAD

**Issue by mandiwise** [redacademy/granville-spring-2017#14]
I would recommend leaving `index.php` as default as possible, because remember, all roads lead back to `index.php` in the WP template hierarchy.

For example, you wouldn't want a "Blog Posts" `<h1>` showing up on a page that had nothing to do with the blog. Use `home.php` to style you blog instead and restore `index.php` to what it was in redstarter.

**Comment by kmsolberg** [comment]
index.php reset to the default and we're using home.php instead.
