### ISSUE TITLE
Hide default "Posts" if not needed

### ISSUE THREAD

**Issue by mandiwise** [redacademy/granville-spring-2017#3]
If the client doesn't require a blog, you can hide the Posts-related UI elements with this plugin:

https://gist.github.com/mandiwise/2ea571ae0773b340af5a

**Comment by wtLau** [comment]
The client needs a blog post. Just confirmed a new layout  with designers, working on it now.

**Comment by rcass** [comment]
Alright sounds good. Just close this issue once you have finished building that blog. Since blog functionality is built into WordPress, this feature should not take long to implement.
