### ISSUE TITLE
Use custom fields for gallery posts instead of default WYSIWYG

### ISSUE THREAD

**Issue by mandiwise** [redacademy/granville-spring-2017#4]
Please replace the WYSIWYG editor on your gallery posts with a CFS loop field that contains an image upload input. I would recommend also implementing a radio button or checkbox field to allow the client to choose the featured gallery image (rather than using the default featured image field).

The reason this needs to be done is because the way you have currently set this up is very fragile and it would be very easy for the client to accidentally break this.

**Comment by wtLau** [comment]
Use custom fields for gallery posts instead of default WYSIWYG 

commit# :
f3cf6a2063b98ead6e47145d125126299d3c4236, dc8ad0cf16c73b1025575894b7444c3a2f054917, aa25ae46a43a26493fe25c82036a94936064db25, 510b977267d95881962c6cb0df3e17ee6e7040f8, 651c127690e576d7d0e2fa5da7421568d62d92e5
